# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: aws-direct-integrations
frameworkVersion: '2'

app: process-automation

custom:
  serverless-offline:
    httpPort: 8000
    useChildProcesses: true
  prune:
    automatic: true
    number: 1
  # client:
  #   bucketName: web-chat-demo-s3-bucket
  #   distributionFolder: html/

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  profile: ccportal
  region: eu-central-1
  deploymentBucket: my.${self:provider.stage}.serverless.deploys
  versionFunctions: false
  tracing:
    lambda: true
  logRetentionInDays: 7
  timeout: 30

functions:
  conversationDump:
    handler: handler.conversationDump
    events:
      - http:
          path: conversation-dump
          method: post
          cors: true

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - serverless.yml
    - .serverless/**
    - requests/**
